### ISSUE TITLE
Allow usage from .ssh/config's ProxyCommand

### ISSUE THREAD

**Issue by xtaran** [tiwe-de/ssh-agent-filter#8]
Hi,

I fear that the following is not possible, but I might be wrong:

It would be nice if I could use e.g. `Host` and `ProxyCommand` inside `.ssh/config` to configure for which hosts which keys should be passed.

Just looking at the order of steps `ssh -v` shows, it should be possible because configuration parsing comes before any key or agent handling.

Feel free to close this issue unsolved in case it's technically not possible or out of scope for this project.

**Comment by tiwe-de** [comment]
No, these are two different types of proxy here: one for the connection to the ssh server (`ProxyCommand`) and one for the connection to the `ssh-agent` (`ssh-agent-filter` via `SSH_AUTH_SOCK`).

But you may use options like `--rsh` for `rsync` or `core.sshCommand` / `GIT_SSH_COMMAND` for `git` to select `afssh` or even a custom wrapper that parses `.ssh/config` for `IdentityFile` or comments with custom options. If you develop such a wrapper please send a patch to include it here.

If your problem is that ssh tries too many public keys (from the agent), you might have to set `IdentitiesOnly yes` in `.ssh/config`.
